apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      labels:
        app: payments-ms
    spec:
      containers:
      - image: europe-southwest1-docker.pkg.dev/nestjs-microservices-479616/images-registry/payments-ms:latest
        name: payments-ms
        env: 
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats:4222"
        - name: STRIPE_SUCCESS_URL
          value: "https://localhost:3000/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "https://localhost:3000/payments/cancel"
        - name: STRIPE_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: STRIPE_SECRET      
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: STRIPE_WEBHOOK_SECRET
        resources: {}
status: {}
