version: '3'

services:
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3000
  nats-server:
    image: nats:2.10-alpine
    ports:
      - "8222:8222"
  products-ms:
    build:
      context: ./products-ms
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:docker
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3001
      - DATABASE_URL=file:./dev.db
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:docker
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3002
      - DATABASE_URL=${ORDERS_DB_URL}
    depends_on:
    - orders-db
    
#LOCAL DB
  orders-db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders_db
    volumes:
      - ./orders-db/postgres:/var/lib/postgresql/data
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:docker
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3003
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: Dockerfile
    ports:
      - 3004:3004
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:docker
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3004
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}