apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders-ms
  name: orders-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms
  strategy: {}
  template:
    metadata:
      labels:
        app: orders-ms
    spec:
      containers:
      - image: europe-southwest1-docker.pkg.dev/nestjs-microservices-479616/images-registry/orders-ms:latest
        name: orders-ms
        env: 
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats:4222"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: orders-secrets
              key: DATABASE_URL
        resources: {}
status: {}
